### ISSUE TITLE
 Fig3.3 | simpsons_paradox.ipynb | Book1

### ISSUE THREAD

**Issue by nitish1295** [pyprobml-review/pyprobml-review#16]
Working on this

**Comment by patel-zeel** [comment]
Hi @nitish1295, as discussed over chat, you can pick up the next figure!

**Comment by nitish1295** [comment]
Hi @patel-zeel 

I already did, a PR is submitted for the next one at https://github.com/pyprobml-review/pyprobml-review/pull/15.

This is the one I am currently working on, will provide an update on this soon

**Comment by nitish1295** [comment]
The notebook for this figure is already complete. Will take a different figure
