### ISSUE TITLE
Fig2.14 (Book1) linreg_1d_hetero_tfp.ipynb_10/5

### ISSUE THREAD

**Issue by GautamV234** [pyprobml-review/pyprobml-review#3]
I am working on this figure

**Comment by TakshPanchal** [comment]
May I take this issue?

**Comment by karm-patel** [comment]
Yes, sure.

**Comment by TakshPanchal** [comment]
In the current implementation, they have used Keras to build a sequential model and train it. Should I use FLAX instead of Keras?

**Comment by karm-patel** [comment]
> In the current implementation, they have used Keras to build a sequential model and train it. Should I use FLAX instead of Keras?

Yes, FLAX would be useful.
