### ISSUE TITLE
Fig 2.9 & 2.10 | Book 2

### ISSUE THREAD

**Issue by TakshPanchal** [pyprobml-review/pyprobml-review#67]
![image](https://user-images.githubusercontent.com/52617262/175763704-03687cc7-26cf-4c5c-acbf-f8bb6e7ed708.png)

**Comment by TakshPanchal** [comment]
I am working on this figure.

**Comment by TakshPanchal** [comment]
Can you suggest the height of the fig 2,9?

**Comment by TakshPanchal** [comment]
From [dashboard_figures_book2.md
](https://github.com/probml/pyprobml/blob/workflow_testing_indicator/dashboard_figures_book2.md)  I used `fig_height=2.5`. 
![image](https://user-images.githubusercontent.com/52617262/175810233-2fd6a3c6-4fd7-4234-ae13-297c2b57fb3a.png)

**Comment by karm-patel** [comment]
Yes yes sure, you don't need to ask for PR in review repo, because many time I missed to see comments in issues.

**Comment by karm-patel** [comment]
Btw add `xlabel` & `ylabel` in both figures
