### ISSUE TITLE
Fig 2.15 of book 2

### ISSUE THREAD

**Issue by TakshPanchal** [pyprobml-review/pyprobml-review#98]
![image](https://user-images.githubusercontent.com/52617262/176606257-35975560-1bd5-4aa6-9562-bbc2d3d725e6.png)

**Comment by TakshPanchal** [comment]
I am working on this fig.

**Comment by TakshPanchal** [comment]
Hey @karm-patel, while latexifing the figure, I found that one of the distributions is the exponential distribution. In `jax.scipy.stat.expon` doesn't have `cdf` function.

**Comment by karm-patel** [comment]
you can use `tensorflow_probability` like below, you an replace stats with this module

![image](https://user-images.githubusercontent.com/59387624/176619027-a09c2078-7fe8-49de-b1a3-a2d8276e5b7c.png)
